### ISSUE TITLE
When you will release the code

### ISSUE THREAD

**Issue by deepseek** [AnonyCode111/TextRSN#1]
@AnonyCode111 @anoycode22 
Thank you for your hard work,

When do you expect you will  release the training and inferencing code?

Feel free to close this issue

**Comment by GXYM** [comment]
Thank you for your attention. All code will be open source when the paper is officially published or accepted and the boss agrees

**Comment by AnonyCode111** [comment]
> @AnonyCode111 @anoycode22
> Thank you for your hard work,
> 
> When do you expect you will release the training and inferencing code?
> 
> Feel free to close this issue



Thank you for your attention. We will open source all the code when my thesis is officially accepted or published and approved by the boss

**Comment by deepseek** [comment]
wishing you good
